### ISSUE TITLE
How to generate new Keys?

### ISSUE THREAD

**Issue by Banquo1** [beyondcode/laravel-websockets#101]
Hi there,
I'am switching from pusher and it just works great! But now I want to add another App. How dow I generate a new  id / key / secret ?

Thanks!

**Comment by stayallive** [comment]
You can use any values you like 👍 

So using [random](https://www.random.org/passwords/?num=5&len=24&format=html&rnd=new) values will work just fine!

I don't think there are any requirements. Just don't make the secret something guessable. The app ID is less important since that is public information.
