### ISSUE TITLE
Pusher API on the frontend

### ISSUE THREAD

**Issue by da3monHunter** [beyondcode/laravel-websockets#104]
I'm sorry i don't understand this package fully so i must be doing it wrong.
There is a chat package called [Talk](https://github.com/nahid/talk) for laravel, it uses pusher for Realtime communication and whenever i configure the laravel part of that package to use laravel-websockets it doesn't work in realtime as in browsers console i see the 'pusher.js' trying to connect to '<cluster>.pusher.com' hence failing.
Please educate me on this matter, Regards.

**Comment by stayallive** [comment]
Pusher JS also needs to be configured to use the correct server (yours not theirs).

Talk seems to be able to handle that looking at the view: https://github.com/nahid/talk/blob/17c2ba4529bb5690054aeb156a16f996028c2d21/src/views/pusherjs.blade.php

Those options are coming from the configuration file: https://github.com/nahid/talk/blob/17c2ba4529bb5690054aeb156a16f996028c2d21/src/helpers/talk.php#L13

So you probably need something like this (I removed all config keys that are irrelevant for the JS pusher options, they are still needed):

```php
return [
    'broadcast' => [
        'pusher' => [
            'options' => [
                'wsHost' => 'yoursocketserverhost',
    			'wsPort' => 6001,
			    'wssPort' => 6001,
			    'encrypted' => true,
			    'disableStats' => true,
			    'enabledTransports' => ['ws', 'wss'],
            ]
        ]
    ],
];
```

The above assumes SSL and port 6001, play with this as needed for your setup.

Please note I did not do any testing on this but looking at the code this is where to start looking to figure out how to make it work. Otherwise open an issue on Talk since this could maybe be a nice addition to their documentation on how to configure this package server in their app.
