### ISSUE TITLE
"{"error":"Unknown app id `` provided."}"

### ISSUE THREAD

**Issue by 33sKamal** [beyondcode/laravel-websockets#126]
Hello i followed all steps one by one 
Also some tutorials 
and got this message

----------
"{"error":"Unknown app id `myid` provided."}"
----------

**Comment by stayallive** [comment]
Well, I hate to say it but do double check again you are trying to connect with the same app key as the one you configured in `config/websockets.php`.

Some pointers: https://github.com/beyondcode/laravel-websockets/issues/76#issuecomment-451661101

It's most likely a configuration issue and `myid` doesn't exist.

Als make sure to restart `php artisan websockets:serve` if you make configuration changes.

**Comment by 33sKamal** [comment]
i tried but nothing new 
it works fine locally 
but fails  when trying to use it with homestead

**Comment by ldavidsp** [comment]
@stayallive run `php artisan config:cache`

**Comment by stayallive** [comment]
@ldavidsp I was not the one with the issue in the first place, also this issue is 2 years old 😅

But most important of all, please do not suggest running `config:cache` unless you also explain what this does but suggest running `php artisan config:clear` to clear the configuration cache feature of Laravel that might have been enabled by accident. If that solves the problem you can always re-enable it using `php artisan config:cache`.
