### ISSUE TITLE
403 Forbidden on Laravel Serve

### ISSUE THREAD

**Issue by abhiburk** [beyondcode/laravel-websockets#133]
I followed exact docs but still I am getting some weird error on my Laravel Server.
Now when I hit `127.0.0.1:8000/laravel-websockets/` I get 403 Forbidden error which I found in Authorize Class of vendor folder.
So I `dd($request->user())` and it has login user data but still it gives me `abort(403)` error.
When I directly return `$next($request);` it works like charm but I am not satisfied with my solution their has to be some reason for this situation. Kindly help me out. Thank You.

```
class Authorize
{
    public function handle($request, $next)
    {
        return $next($request);
        //return Gate::check('viewWebSocketsDashboard', [$request->user()]) ? $next($request) : abort(403);
    }
}
```

**Comment by Catzilla** [comment]
This happened because you did not setup Gate, which validates user permission to access the dashboard.

If you want to make dashboard available for all logged users, add the following to the `boot` method inside your `AuthServiceProvider`:
```php
Gate::define('viewWebSocketsDashboard', function ($user = null) {
    return $user != null;
});
```
Of course, you can make additional checks inside closure.
More info in [documentation](https://docs.beyondco.de/laravel-websockets/1.0/debugging/dashboard.html#protecting-the-dashboard)
