### ISSUE TITLE
Unable to get private channels

### ISSUE THREAD

**Issue by rflatt-reassured** [beyondcode/laravel-websockets#149]
In my function, I connect to pusher and display the channels. Although I have both presence and private ones, it only displays the presence ones:

```
    public function handle()
    {
        $channels = [];
        $pusher = new Pusher(env('PUSHER_APP_KEY'), env('PUSHER_APP_SECRET'), env('APP_NAME'), [
            'host' => config('broadcasting.connections.pusher.options.host'),
            'port' => config('broadcasting.connections.pusher.options.port'),
        ]);
        $response = $pusher->get('/channels');
        dd($response);
    }
```

This returns:
```
array:3 [
  "body" => "{"channels":{"presence-url.leadenquiries.view.4429331":{"user_count":1}}}"
  "status" => 200
  "result" => array:1 [
    "channels" => array:1 [
      "presence-url.leadenquiries.view.4429331" => array:1 [
        "user_count" => 1
      ]
    ]
  ]
]
```

The dashboard shows two occupied private channels which aren't returned:

![laravel websockets](https://user-images.githubusercontent.com/26278889/56037743-f9f1ec80-5d27-11e9-87da-e8a0bf3ad9a8.jpg)

**Comment by francislavoie** [comment]
That's because the non-presence channels are filtered out here: https://github.com/beyondcode/laravel-websockets/blob/master/src/HttpApi/Controllers/FetchChannelsController.php#L15

Thir PR https://github.com/beyondcode/laravel-websockets/pull/127 should fix it, once merged. In the meantime, if you need it right away, you can make a fork with those changes.
