### ISSUE TITLE
How to scale over 100 000 concurrent connections 

### ISSUE THREAD

**Issue by Barraud-Samuel** [beyondcode/laravel-websockets#207]
Hi,
I wan't to know if it's possible and how to enable over **100K** concurrent connections on a laravel app. I've read this https://docs.beyondco.de/laravel-websockets/1.0/faq/deploying.html and this https://docs.beyondco.de/laravel-websockets/1.0/faq/scaling.html but i don't find out how they can go over 10K concurrent connection ? 
For the hosting i planned to use google cloud run 

thx :)

**Comment by francislavoie** [comment]
Keep an eye on https://github.com/beyondcode/laravel-websockets/pull/140 or pull the code and try it out for yourself.

When running a single instance of laravel-websockets, you'll quickly hit connection limits due to all kinds of factors, like hardware/network limits, file handle limits, etc. Scaling by running more instances will allow you to hit much higher concurrent connection counts.
