### ISSUE TITLE
How to detect on disconnect to trigger an event

### ISSUE THREAD

**Issue by nicolasvahidzein** [beyondcode/laravel-websockets#217]
Hello,

can someone help me find some good docs on how we would go about listening to the disconnect events and pass it on to laravel for some processing?

Thank you very much.

This link does not have enough info for me: https://docs.beyondco.de/laravel-websockets/1.0/advanced-usage/custom-websocket-handlers.html

**Comment by francislavoie** [comment]
- Make a class that extends `BeyondCode\LaravelWebSockets\WebSockets\WebSocketHandler`
- Override the `onClose` method (don't forget to call `parent::onClose($connection)`), adding your custom logic.

The next part is really up to you. It depends what you want to do with the event and what you want to have happen. Since `laravel-websockets` is an async event loop, you want to avoid doing any blocking IO during execution. Because of this, you'll need to carefully consider what you want to do.

Some ideas:
- If you use Redis, then you could install https://github.com/clue/reactphp-redis which is an async Redis client implementation compatible with ReactPHP, which `laravel-websockets` is based on. You'll need to boot up the Redis connection (see https://github.com/beyondcode/laravel-websockets/pull/140/files#diff-935afc5303dbc9f633e5b5c8566f51beR62-R72 and https://github.com/beyondcode/laravel-websockets/pull/140/files#diff-4ecbfadc9c20bccc06783754b39a98a9R141-R155 for some code examples, you might also need to override `StartWebSocketServer` as well as a separate artisan command so that you can initialize Redis) and from there you can fire off a message to push something to Redis. You could go the extra mile of engineering a way to push a job onto the queue if you use the Redis queue driver, but that'll require a bunch of extra work because Laravel doesn't support `redis-react` as a driver. From there, that job could just do whatever.
- Similarly, you could use https://github.com/friends-of-reactphp/mysql and fire off a query to write something to the DB, if that's what you need to do.
- If you need to do some file IO, you could use https://github.com/reactphp/filesystem
- If all you want to do is send another websocket message to another connected client, then that part should be super easy. In your class that extends `WebSocketHandler`, you have access to `$this->channelManager` which you can use to get the Channel object and then broadcast a message to it to all the connected clients.

So uh... yeah. Good luck! 😛

**Comment by nicolasvahidzein** [comment]
@francislavoie Thank you for this wonderful writeup Francis. I was able to read a ton of the issues in this repo and found a way to extend laravel websockets like you mentionned. My only step that was left was accessing in the onclose event (which i can now detect) the user that disconnected. That is the missing piece!! 

Any ideas? Thank you so much once again.

**Comment by francislavoie** [comment]
What are you actually trying to do with that information though? That's important to how it'll be implemented.

**Comment by nicolasvahidzein** [comment]
i want to disconnect that user as soon as he closes the window. When they log of gracefully by using the logout button or when they session is left idle i can notify the back end to disconnect them. When they close the browser or window i cannot do any thing and they are left "online". I would love your input.

**Comment by francislavoie** [comment]
Disconnect from what exactly?

**Comment by nicolasvahidzein** [comment]
There are 2 parts. He gets disconnected from the chat app (i'm not using presence channels feature for this because i need a global mechanism), and also from the application itself.

When my users connect they are marked as online and monitored through then on in the backend.

The only thing i cannot track is messy logoff by browser close.

**Comment by francislavoie** [comment]
First of all, you'll need to use presence channels, because that's the only way you'll be able to track users on the websocket server.

Secondly, you can probably do something like:

- Extend `ArrayChannelManager`, change `config/websockets.php` `channel_manager` to your class
- Override `removeFromAllChannels` (calling `parent::removeFromAllChannels($connection)`)
- Do something like this
    ```php
    $user_id = collect(Arr::get($this->channels, $connection->app->id, []))
        ->filter(function (Channel $channel) {
			return $channel instanceof PresenceChannel;
        })
        ->map(function (PresenceChannel $channel) {
            return $channel->getUsers();
        })
        ->filter(function (array $users) use ($connection) {
            return isset($users[$connection->socketId]);
        })
        ->map(function (array $users) {
            return $users[$connection->socketId]->user_id;
        })
        ->first();
    ```

Looks kinda crazy, but I THINK it should work. You'll need to try it out, I just hacked this together real quick.

**Comment by nicolasvahidzein** [comment]
I think what i implemented is actually much simpler and more elegant that all of this. I'd love to show you. I did a heartbeat system and a clean up function on the backend.

**Comment by dereck22dev** [comment]
> Je pense que ce que j'ai implémenté est en fait beaucoup plus simple et plus élégant que tout cela. J'aimerais vous montrer. J'ai fait un système de pulsation et une fonction de nettoyage sur le backend.

Bonjour j'ai le même problème également pourrais-tu m'en dire plus sur comment tu l'a résolue? merci.
