### ISSUE TITLE
[Question] How to prevent User for having multiple connection in a single presence channel

### ISSUE THREAD

**Issue by ronmrcdo** [beyondcode/laravel-websockets#246]
How to prevent User having multiple connection in a single channel?

ex. I login as user 1 then I open incognito or my smartphone then login the same account? how can I prevent it, thanks

**Comment by stri8ed** [comment]
Looks like this would require implementing your own [StatisticsLogger](https://github.com/beyondcode/laravel-websockets/blob/9ce2cc3ff7604eea872e1c3a52165d77b9b03a47/src/Statistics/Logger/StatisticsLogger.php), and then listening on the `disconnection` and `webSocketMessage` events, to maintain a list of open channel connections (perhaps persisted in Database).

Once you have this in place, during channel authorization, you can verify that the user is not already connected to the channel, otherwise, reject the authorization request.

**Comment by stri8ed** [comment]
Essentially, you need to maintain a list of connected users, per-channel (in a database), and then validate that user is not already connected in your channel Authorization method. 

You could in theory maintain such a list, by extending `BeyondCode\LaravelWebSockets\WebSockets\WebSocketHandler`, and keeping track whenever user joins a channel or disconnects. Be sure to bind your custom handler [to your router](https://docs.beyondco.de/laravel-websockets/1.0/advanced-usage/custom-websocket-handlers.html).
