### ISSUE TITLE
Is there browser security that could block connection to the websocket?

### ISSUE THREAD

**Issue by sbkl** [beyondcode/laravel-websockets#281]
I followed this tutorial from @stayallive to setup Laravel Websockets in production with SSL certificate and it is working great on my personal mac browsers:
[https://alex.bouma.dev/installing-laravel-websockets-on-forge/](installing-laravel-websockets-on-forge)

However, when I try it on a windows laptop from my company, it can't connect.

For instance with Chrome, I have the same version installed. Mac is 64 bits while windows is 32 bits. But I don't think this makes a difference?

Makes me wondering. Is there some security parameters in web browsers that would block such connection? If yes, how to authorize it? Maybe for specific website?

**Comment by stayallive** [comment]
Not much info to go on from your issue...

It might help if you could tell us what the error is your seeing in your console when the connection fails or with what error the websockets request fails.

If there is no error at all that you can see, check out this section: https://alex.bouma.dev/installing-laravel-websockets-on-forge/#a-note-about-ports which explains a little about getting the errors from inside the pusher client.

My best guess is though that you might be using a port your corporate firewall is blocking since you say it's only not working on you company laptop.

In my post there are also 2 links to example applications, you could check and see if they are working and try and use the port I am using there.

**Comment by rennokki** [comment]
Bump
