### ISSUE TITLE
Help with deployment on Laravel Forge w/ let's encrypt

### ISSUE THREAD

**Issue by Eldair** [beyondcode/laravel-websockets#30]
Hello,

Could someone help with how to configure the app to work on laravel forge w/ let's encrypt? The app would host it's own websocket, so it's not a separate subdomain.

**Comment by sudden-break** [comment]
I have the same situation. I got it working on local with my self signed certs from valet, but can't get it working on my forge server.
I also tried to open port 6001 on the forge firewall setup, but:
"WebSocket connection to 'wss://xxx:6001/app/a8f4975fa8b8dd5da1ca?protocol=7&client=js&version=4.3.1&flash=false' failed: WebSocket opening handshake timed out"

**Comment by coolcodemy** [comment]
Disclosure, I am a RunCloud owner. Since I saw this package, we have modified our nginx config to allow a user to add their own proxy setting. In this case, Let's Encrypt will work on port 443 which proxying port 6001. I think you can suggest forge to allow this kind of modification.

**Comment by pimski** [comment]
Hey @Eldair and @sudden-break 

I'm still trying to get things working locally (windows + homestead). I got a similar error as you guys. So I tried to connect to my local homestead server on port 6001 using telnet. This didn't work. However, if I run the sockets server on my "external" ip address I am able to connect:
```
artisan websockets:serve --host=192.168.10.10
```
I am getting other errors now, but that's inside php code, so getting closer... Also, I don't know the implications of running it this way since I'm not a server specialist. So I'll have to read up on server stuff I guess :-)

**Comment by Eldair** [comment]
I think that the easiest solution would be to replace forge's current let's encrypt system with certbot, which would let us have a permanent cert. path instead of the current (ever changing) one.

**Comment by stayallive** [comment]
I think the easiest method is to add a new host to forge (socket.yourdomain.tld for example) which has it's own cert and add the nginx rules to it to proxy the traffic from your server running on port 6001 (plain, no https) and let nginx do all the https stuff: https://docs.beyondco.de/laravel-websockets/1.0/basic-usage/ssl.html#usage-with-a-reverse-proxy-like-nginx

Replae the `location /` in the Forge nginx config with (assuming you are running the websocket server on port 6001 which should be the default):

```
  location / {
    proxy_pass             http://127.0.0.1:6001;
    proxy_set_header Host  $host;
    proxy_read_timeout     60;
    proxy_connect_timeout  60;
    proxy_redirect         off;

    # Allow the use of websockets
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection 'upgrade';
    proxy_set_header Host $host;
    proxy_cache_bypass $http_upgrade;
  }
```

This way Forge can manage the certificate itself and you don't have to worry about it 👍 (and also don't have to open any special ports on the server).

**Comment by acacha** [comment]
Hello,

One question: how can I test I'have configured Reverse Proxy ok? For example with following config:

```
$ cat /etc/nginx/sites-enabled/00_socket.scool.cat
server {
  listen        443 ssl;
  listen        [::]:443 ssl;
  server_name   socket.scool.cat;

  # Start the SSL configurations
  # ssl                  on;
  ssl_certificate      /etc/nginx/ssl/scool.cat/412609/server.crt;
  ssl_certificate_key  /etc/nginx/ssl/scool.cat/412609/server.key;

  location / {
    proxy_pass             http://127.0.0.1:6001;
    proxy_set_header Host  $host;
    proxy_read_timeout     60;
    proxy_connect_timeout  60;
    proxy_redirect         off;

    # Allow the use of websockets
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection 'upgrade';
    proxy_set_header Host $host;
    proxy_cache_bypass $http_upgrade;
  }
}
```
If i visit:

https://socket.scool.cat/

thows my a 502 Bad Gateway error.

**Comment by vesper8** [comment]
@stayallive thank you for your explanation.. but honestly my head is spinning trying to wrap my head around all this! I think your solution seems the best and cleanest.. but can you please see if I understand correctly

currently on my dev, using laravel valet with the --secure flag

I have 3 apps
#1 socket.tld.dev which handles the websocket, this has a .crt and .key in the websockets.php config in order to make it work

#2 restapi.tld.dev which is the api for my front-end, and can broadcast to the front-end, via the dedicated socket app

#3 vue-frontend.tld.dev which is my front-end, this uses host: socket.tld.dev and connects over ssl

all 3 sites were https through Valet and it works great

now I tried to move all of this to my forge server and I can't connect. I realized the websocket ssl config was still pointing to my dev's .crt/.key so that was surely problem #1, and problem #2 is that I probably need to open up port 6001 first

But then I came here and saw your solution and it seems great since I may not have to do either of those things above.. worry about certs and open up a port

I already set up my 3 subdomains and made them all https through letsencrypt

Now is it my understanding that you're suggesting I set up a 4th subdomain, http only, and use the nginx block you provided to proxy to my internal port 6001 ?

Does this 4th domain need to be https with let's encrypt?

And then inside my socket.tld websocket's config I can leave the ssl config blank ?

And then in my vue-frontend I would set the host to https of this 4th domain?

This way all my domains are still https, and I can access my debug dashboard on the socket.tld, but the websocket config itself is not "SSL" thanks to the proxy trick?

**Comment by stayallive** [comment]
@vesper8 you're almost there. The socket.tld.dev app you have should be it's own subdomain (with https) with that nginx block I mentioned earlier.

You will also need to run the `php artisan websockets:serve` command in Supervisor using the Daemons tab on your Forge server dashboard.

This way the websockets server runs on 127.0.0.1:6001 on your Forge box (do not configure SSL in your websockets.php file for the sockets server).

Then any app on your server (a server side app) can talk to your websockets server on http://127.0.0.1:6001 (no https) or socket.tld.dev:443 (with ssl). The internal non-http path will be slightly faster since it doesn not go via the internet but only local network.

Your front-end clients should connect to socket.tld.dev:443 (with http).

That should be it 👍 

A reverse proxy... proxies traffic, you might already guessed that but a default https host listens on port 443 and what that `proxy_pass http://127.0.0.1:6001;` does in the nginx config is pass any traffic on to `http://127.0.0.1:6001` which is your local `php artisan websockets:serve`. So nginx handles the SSL/TLS stuff and passes un-encrypted content through to your websockets server which handles the connections. This way port 6001 does not need to be exposed and your websockets server does not have to handle the SSL/TLS handshakes itself.

Hope this makes more sense now for everyone 👍

**Comment by stayallive** [comment]
@acacha if your are getting a 502 the `proxy_pass` failed. Make sure you have the `php artisan websockets:serve` running and it's running on 127.0.0.1 and port 6001. The config looks fine at a glance.

**Comment by stayallive** [comment]
Again, you should _not_ add the certificate in websockets.php 👍 

Let nginx handle the SSL, run the websockets server as a plain one.

You are doing a `proxy_pass http://127.0.0.1:6001;` but that will fail if your websockets server expects a https connection.

**Comment by acacha** [comment]
Oh thanks I'm sure I've tried this combination but not at least no more 502 gateway errors. Thanks! Let met try it in deep and If it works i will try to put here my full config for anybody like me with similar problems.

**Comment by acacha** [comment]
Working on it but now I have a 504 timeout error instead of 502 Bad gateway:

```
curl https://socket.scool.cat/
<html>
<head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx/1.15.6</center>
</body>
</html>

```

**Comment by acacha** [comment]
Also not working with Laravel Echo:

Laravel Echo config:

```
window.Echo = new Echo({
  broadcaster: 'pusher',
  key: '6f627646afb1261d5b50',
  wsHost: 'socket.scool.cat',
  disablestats: true,
  encrypted: true
})
```

Chromer Console error:
```
app.js:38721 WebSocket connection to 'wss://socket.scool.cat/app/6f627646afb1261d5b50?protocol=7&client=js&version=4.3.1&flash=false' failed: WebSocket is closed before the connection is established.
```

**Comment by acacha** [comment]
More info:https://github.com/beyondcode/laravel-websockets-docs/pull/1

**Comment by acacha** [comment]
Sorry 504 Gateway error resolved:

Changed in /etc/nginx/sites-available/00_socket.scool.cat:

```
  location / {
    proxy_pass             https://127.0.0.1:6001;
....
```

to http://127.0.0.1:6001; (without s)

**Comment by vesper8** [comment]
@stayallive thank you very much for your help! I have it all working perfectly now using your solution!

I did end up creating a 4th subdomain for the proxy pass, because the socket.tld domain still needs to be accessible for the sole purpose of accessing the debug dashboard

**Comment by stayallive** [comment]
@vesper8 ah yeah, ofcourse! Happy you got it working 🤘

**Comment by hadlow** [comment]
Hello!

I seem to be having trouble with the same thing. I am trying to setup the reverse proxy as explained in these posts, and am getting a 502 error. I have created another Site in Forge, with the domain socket.domain.tld and this is the nginx config for that site:
`# FORGE CONFIG (DO NOT REMOVE!)
include forge-conf/socket.domain.com/before/*;

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name socket.domain.com;

    # FORGE SSL (DO NOT REMOVE!)
    ssl on;
    ssl_certificate /etc/nginx/ssl/socket.domain.com/471603/server.crt;
    ssl_certificate_key /etc/nginx/ssl/socket.domain.com/471603/server.key;
    
    # FORGE CONFIG (DO NOT REMOVE!)
    include forge-conf/socket.domain.com/server/*;

    location / {
        proxy_pass             http://127.0.0.1:6001;
        proxy_read_timeout     60;
        proxy_connect_timeout  60;
        proxy_redirect         off;
        
        # Allow the use of websockets
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}

# FORGE CONFIG (DO NOT REMOVE!)
include forge-conf/socket.domain.com/after/*;`

In my config/websockets.php file, the local_cert nad local_pk are both set to null.

My pusher connection config in config/broadcasting.php looks like this:

`'pusher' => [
            'driver' => 'pusher',
            'key' => env('PUSHER_APP_KEY'),
            'secret' => env('PUSHER_APP_SECRET'),
            'app_id' => env('PUSHER_APP_ID'),
            'options' => [
                'cluster' => env('PUSHER_APP_CLUSTER'),
                'host' => env('WS_HOST', '127.0.0.1'),
                'port' => env('WS_PORT', '6001'),
                'scheme' => env('WS_SCHEME', 'http'),
                'encrypted' => env('WS_ENCRYPTED', 'false'),
            ],
        ],`

With my .env file looking like:

`WS_HOST=127.0.0.1
WS_POST=6001
WS_SCHEME='https'
WS_ENCRYPTED=true`

My Echo config:

`window.Echo = new Echo({
			broadcaster: 'pusher',
			key: 'PUSHE_KEY',
			encrypted: true,
			wsHost: socket.domain.com,
			wsPort: 443,
			wssPort: 443,
			disableStats: true,
			authEndpoint: environment.url + '/broadcasting/auth',
			auth: {
				headers: {
					Authorization: 'Bearer ' + this.authService.getBearer(),
				},
			},
		});`

And the exact error I get in the Chrome console:

`WebSocket connection to 'wss://socket.domain.com/app/b7c07386f4d71d126430?protocol=7&client=js&version=4.3.1&flash=false' failed: Error during WebSocket handshake: Unexpected response code: 502`

Oh, and I have the `php artisan websockets:serve` command setup as a Forge Daemon.

Any pointers on this will be more than appreciated, thanks in advance

**Comment by jafar-albadarneh** [comment]
@stayallive since a lot of us is experiencing the same problem, i think it would be great if there is a blog post / gist that goes through an end-to-end configuration to get it working properly.
I've been digging in such issue for almost a week now.

Appreciated!

**Comment by hadlow** [comment]
Thanks @stayallive ! Your guide helped me get it working 🎉

**Comment by jafar-albadarneh** [comment]
@stayallive You made my day! Working Great now. Thanks a lot

**Comment by tshafer** [comment]
Your comments helped me a lot @stayallive 
Thank you.

**Comment by xlcrr** [comment]
Would love to know how to set this up locally using Laravel Homestead before trying to figure it out on forge! Reading up on nginx config now, will post the solution as soon as I can figure it out - unless anyone else already knows it, that would be great ?

**Comment by rymesaint** [comment]
> @jafar-albadarneh how about: https://alex.bouma.me/installing-laravel-websockets-on-forge/

Thank you you helped me a lot
