### ISSUE TITLE
Configure AWS Websocket API

### ISSUE THREAD

**Issue by haric655** [beyondcode/laravel-websockets#354]
How to set up AWS Websocket API  with this laravel-websocket library?

https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-websocket-api.html

**Comment by stayallive** [comment]
> In API Gateway you can create a WebSocket API as a stateful frontend for an AWS service (such as Lambda or DynamoDB) or for an HTTP endpoint. The WebSocket API invokes your backend based on the content of the messages it receives from client apps.

From the docs you linked.

AWS WebSocket API is used to abstract away HTTP/Lambda/DynamoDB and allow those services to be queries/executed using WebSocket messages instead of REST.

I hope that helps in your understanding that the AWS WebSocket API and this package have nothing to integrate/configure because this package provides a Pusher replacement server.
