### ISSUE TITLE
Any example/demo with native WebSocket API?

### ISSUE THREAD

**Issue by jfoliveira** [beyondcode/laravel-websockets#355]
The [documentation](https://docs.beyondco.de/laravel-websockets/1.0/basic-usage/pusher.html#configuring-websocket-apps) makes me think this is a package tight to [Laravel Echo](https://laravel.com/docs/7.x/broadcasting#installing-laravel-echo) javascript client implementation.

However, [this comment on another issue ](https://github.com/beyondcode/laravel-websockets/issues/145#issuecomment-480518542)mentions that
```
You should be able to use any pusher client library to use it from an app. 
```

Is it also possible for a client application to connect to a Laravel Websockets server by using the [browser native WebSocket API](https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API/Writing_WebSocket_client_applications)?

Could you point me to any code example?

**My main use case**: A public API providing notifications (one way, server to client) to third-party apps that consume the API, without the need for the client apps to keep polling API server for updates.

**Comment by stayallive** [comment]
I don't have an answer to your question, but I do want to offer some insight.

`laravel-websockets` is meant to be a Pusher replacement. So I would advice to use the [Pusher JS SDK](https://github.com/pusher/pusher-js) in your apps (or other Pusher provided client libraries) to handle the Pusher protocol specifics instead of implementing it yourself.

**Comment by jfoliveira** [comment]
@stayallive got you. If it aims to be a Pusher replacement, and that's the scope of `laravel-websockets,` it makes total sense to rely on Pusher SDK.
Thank you!
