### ISSUE TITLE
laravel-websockets + ionic 6

### ISSUE THREAD

**Issue by danvfebra** [beyondcode/laravel-websockets#356]
Hi everyone, I just want to ask if this laravel-websockets can be integrated with Ionic?

if so how am I going to do that?

Thanks in advance!

**Comment by stayallive** [comment]
Yes. It's supported on all platforms Pusher supports (mostly).

> https://pusher.com/tutorials/live-poll-ionic

It looks like you "just" add the JavaScript SDK to the Ionic `index.html`.

In the above blog they mention doing:

```js
var pusher = new Pusher('<PUSHER_KEY>', {
    cluster: 'eu',
    encrypted: true,
});
```

Keep in minde you need to add your own configuration to have it work with the `laravel-websockets` server, so `authEndpoint` (when using private channels) & `wsHost` & `wsPort` & `wssPort` just like you would on the browser version otherwise it will still try to connect to the Pusher servers.
