### ISSUE TITLE
Not working with WSL

### ISSUE THREAD

**Issue by RahulDey12** [beyondcode/laravel-websockets#430]
I use wsl for my dev environment & when I am starting the websocket server it is not working

**Comment by rennokki** [comment]
Can you give some more details about the issue?

**Comment by RahulDey12** [comment]
if fails to connect to the websocket port

**Comment by rennokki** [comment]
Closed as there were given too little informations.

**Comment by leroy** [comment]
Hey,

If someone ever runs into this issue.

Make sure to check the 'Resource monitor' app in Windows and check if there's any apps listening on port 6001 in the network tab.

On my end it turned out Windows firewall was blocking this port. Once I turned off the firewall the listening port show up in the Resource monitor.

I'm sure there's a way to add an exception to Windows firewall, I just ended up turning it off.

Hope this helps anyone!

**Comment by yacinegithub** [comment]
same here with laravel 9 sail on windows 10 wsl
