### ISSUE TITLE
Zero Downtime Deployment

### ISSUE THREAD

**Issue by gcw07** [beyondcode/laravel-websockets#49]
So what would be the best way to deploy this using a zero downtime deployment system (such as Deployer, Laravel Envoy, etc.)? The problem would be that you will be running a version of the websockets server using an older version of your site. So say it would be running release 3 when the current site is on release 4. So it will never pick up any changes to your configuration file for example.

Laravel Horizon has the same problem, but it has a terminate console command. So part of your deployment, you just terminate the current running Horizon and supervisord in the background will restart it back up. But it will restart it in the latest release.

Is there any way to terminate the currently running websockets server short of logging into the server and killing the current running process for the server? Thanks.

**Comment by stayallive** [comment]
Well, in theory you could run `supervisorctl restart ws-server` (where `ws-server` is the supervisor job name), assuming you are using supervisor (which you should or something similar to restart the server in case it crashes).

However there is not graceful restart, websocket connections will be closed and up to the clients to reconnect (Pusher JS will do this automatically).

**Comment by francislavoie** [comment]
@gcw07 I think a solution to #6 will help for you - basically you would launch a second instance you would load balance to before closing the old instance. As @stayallive said, the JS should attempt to automatically reconnect to the second instance. But currently there isn't proper support for horizontal scaling, so this won't work cleanly yet.

**Comment by stayallive** [comment]
@francislavoie yes and no 👍 there is no need to do that. 

Once every client re-connects all connections and rooms will be re-populated so the horizontal scaling will not help with zero-downtime deployment since the socket connection will still be aborted and will need to re-connect anyhow.

The horizontal scaling does not transfer the socket connections over to another instance which would really be zero-downtime deployment (where the client connection will not be broken while the server restarts).

So to upgrade simply restart your `php artisan websockets:serve` daemon process. It will need some very fancy connection juggling that PHP might not be even able to do (it probably will) to upgrade in place without aborting the client connections but that will not be solved by #6 I believe.
