### ISSUE TITLE
V2.x Echo here/leaving not triggering

### ISSUE THREAD

**Issue by AugmentBLU** [beyondcode/laravel-websockets#508]
Hello, I just started using Laravel-Websockets and decided to check out v2 as I'll be needing redis and multi-server support.

I noticed that Laravel Echo .here() and .leaving() are not being triggered. It was working in version 1 when I first tested, updated to v2 and both functions have stopped working. I have backed down to v1 again and both functions work again. 

I realise this is still in beta, just wanted to report or see if it was a known issue.

**Comment by AugmentBLU** [comment]
An update on my issue. 

I updated back to v2 and changed the `LARAVEL_WEBSOCKETS_REPLICATION_DRIVER` back to local and everything is working as expected.

When switching back to Redis, I can see the key/value pairs in my Redis DB that relate to the Laravel-Websocket connections so up to this point it is working. What I can't get to work is broadcasting these pairs that will no doubt trigger the here/leaving functions. 

Any pointers on what we should be doing within Laravel to keep an eye on Redis? Usually I have Horizon running but so far this hasn't solved anything.

**Comment by rennokki** [comment]
We are aware that this is caused by the fact that the Redis replication doesn't work with the presence channels and we're working on a fix, as v2 is needed to reach stability.

Horizon is used for queues, and it has nothing to do with the Redis on the Pub/Sub side.

**Comment by rennokki** [comment]
`.leaving()` do get triggered, but `.here()` is not. I have to investigate this.

**Comment by AugmentBLU** [comment]
> `.leaving()` do get triggered, but `.here()` is not. I have to investigate this.

I can confirm, `.leaving()` does work, `.here()` does not. Hopefully a fix can be found soon.

Keep up the great work!

**Comment by rennokki** [comment]
2.x should fix the .here() method :D

Read here the changelog: https://github.com/beyondcode/laravel-websockets/pull/447

Make sure to get a new copy of the config fule.

**Comment by AugmentBLU** [comment]
Nice, the `.here()` method is working. 

I have an issue with broadcasts duplicate but will create another thread if I can't figure out what's going on.

**Comment by vesper8** [comment]
Also just ran into this issue.. `.here()` works but `.leaving()` does not and as a result `.here()` shows a ton of users that are no longer active

Why is this closed @rennokki ?

**Comment by rennokki** [comment]
@vesper8 I will look into it tomorrow. I have reopened this for now as the problems were signaled for `.leaving()`.

If you can, try to use the `redis` mode and see if the bug goes away. If it goes, then the local channel manager should be further debugged.

**Comment by vesper8** [comment]
Hey @rennokki,

I can confirm that using the `redis` mode makes `leaving()` work correctly so that's a yay

However I noticed that prior to switching to `redis`, I had already "joined" with a user who's browser I have closed long ago, but this user remains "online" now

I don't know how to flush this "online" cache ? I don't want to flush all of redis.. and besides this user must be stuck in the "local" mode somehow

It would be useful if there was a command for flushing this data.. you could pass the app id or app name to the command and it would flush everything related to that app ?

On a side note.. I tried running `websockets:flush`, not realizing that this is only related to statistics, and I received this error:

```
Flushing the collected WebSocket Statistics...

   Illuminate\Contracts\Container\BindingResolutionException

  Target [BeyondCode\LaravelWebSockets\Contracts\ChannelManager] is not instantiable.

  at vendor/laravel/framework/src/Illuminate/Container/Container.php:1017
    1013▕         } else {
    1014▕             $message = "Target [$concrete] is not instantiable.";
    1015▕         }
    1016▕
  ➜ 1017▕         throw new BindingResolutionException($message);
    1018▕     }
    1019▕
    1020▕     /**
    1021▕      * Throw an exception for an unresolvable primitive.

      +32 vendor frames
  33  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
```

**Comment by vesper8** [comment]
It would also be useful if the dashboard could confirm which "mode" is being used

Of course it would be super awesome if the dashboard would report more statistics.. such as displaying all channels currently subscribed too.. including public, private and presence channels, and displaying how many connections are included in each

**Comment by rennokki** [comment]
According to the Pusher protocol, there is a maximum amount of 120 seconds since a connection should not pong in order to be automatically be closed: https://pusher.com/docs/channels/library_auth_reference/pusher-websockets-protocol#recommendations-for-client-libraries

Did the connection last more than 120s after you realized the user won't go away from the prsence channel?

**Comment by vesper8** [comment]
Yes.. it's been 13 hours and .here() is still showing users from 13+ hours ago

**Comment by vesper8** [comment]
any update on this @rennokki ? It's been 2 weeks and those users are are still stuck inside the "online" presence channel even though I've rebooted multiple times since then.

At least can you give me an idea of what cache I need to flush to get rid of them?

**Comment by vesper8** [comment]
Figured out how to delete that key. Also made this helper command to flush out all websocket-related keys from the redis cache

```
<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\Redis;

class FlushWebsockets extends Command
{
    protected $signature = 'websockets:flush';

    protected $description = 'Flush Websockets';

    public function handle()
    {
        $apps = config('websockets.apps');

        foreach ($apps as $app) {
            $redisKeys = collect(Redis::keys(sprintf('*%s*', $app['id'])))->each(function ($fullKey) use ($app) {
                $key = str_replace(config('database.redis.options.prefix'), '', $fullKey);
                $this->info(sprintf('[%s] Deleting redis key <%s>', $app['name'], $key));
                Redis::del($key);
            });
        }
    }
}
```

Maybe it would be worth including this command in this package?

**Comment by rennokki** [comment]
I will need to find a way to integrate this command for the Redis part only, or at least write an endpoint in the server that can be HTTP called and flush them using some kind of authorization.

Enhancement: Regarding the issues with the flushing, I assume your cluster doesn't allow you to call `SMEMBERS`, `SREM`, `ZREM`, or `HDEL` since these are the commands used to remove users, either from the presence or keeping tracking of the socket IDs internally in the Redis instance.

There is a Redis-related bugfix too prior to `-beta.30`. Not sure if this really helps.

**Comment by rennokki** [comment]
@vesper8 So the issue was actually because of a hard stop of the process. I have implemented a while back a way to listen to PCNTL signals and make sure to close any new connections to that specific instance and mark all connections as closed to the channel manager.

However, I plan on fixing the stale data regarding the stored presence channel users by searching for users that have sockets opened, older than 2 minutes (as described in Pusher Protocol Reference), so this way we can clean up all the stale members.

**Comment by vesper8** [comment]
excellent catch @rennokki : ) so happy this project is evolving the way it is and largely thanks to your efforts! As always I look forward to your future releases. Keep up the fine work!

**Comment by vesper8** [comment]
> @vesper8 So the issue was actually because of a hard stop of the process. I have implemented a while back a way to listen to PCNTL signals and make sure to close any new connections to that specific instance and mark all connections as closed to the channel manager.
> 
> However, I plan on fixing the stale data regarding the stored presence channel users by searching for users that have sockets opened, older than 2 minutes (as described in Pusher Protocol Reference), so this way we can clean up all the stale members.

This is still happening to me all the time.. I have users still in the presence channel that don't even exist anymore in the users table. So I'm guessing you haven't had the chance to implement the above fix yet. I hope it's on the roadmap to be added soon.

In the meantime is there a workaround short of manually flushing Redis every so often?
