### ISSUE TITLE
[2.x] Support for encrypted private channel

### ISSUE THREAD

**Issue by radudiaconu0** [beyondcode/laravel-websockets#658]
Maybe support for Encrypted Private Channel (like pusher https://pusher.com/docs/channels/using_channels/encrypted-channels ) can be added. I dont know if its possible but it could be useful.

**Comment by morloderex** [comment]
@radudiaconu0 I just did a test of this with the current 2.x branch. 
And because of all of the decryption and encryption happens in aginst the consumers of this package's application (e.g your application implementing this package).

I managed to get it to work without any changes, the only changes that really is required here is to make sure that the `shared_secret` used for encryption and decryption is sendt along with the authentication request everything else should work like a normal private application. But instead of you app sending the plain data it sends 3 keys `nonce` and `ciphertext` as the event data. 

But this is all handled for you by the pusher-js library if you import the pusher/with-encryption instead of the `normal` pusher library.

**Comment by radudiaconu0** [comment]
@morloderex  so you are not required to implement Something like EncryptedPrivateChannel.php or something like that?

**Comment by morloderex** [comment]
@radudiaconu0 As far as i can tell no, i can upload my testing code to a public repo if you want to have a closer look at it?

**Comment by radudiaconu0** [comment]
yeah it will be cool to see some tests;) i mean i could need this feature for one of my projects;)

**Comment by radudiaconu0** [comment]
@morloderex so could you please upload the tests ? ;)
