### ISSUE TITLE
[2.x] Target [... OutputInterface] is not instantiable while building [...WebSocketsLogger}

### ISSUE THREAD

**Issue by simonbuehler** [beyondcode/laravel-websockets#661]
Hi,

 when trying to add a custom route via 
`WebSocketRouter::get('/apps/{appId}/my-websocket', MyCustomWebSocketHandler::class);` where
`class MyCustomWebSocketHandler implements MessageComponentInterface`
the server won't start with the same exception as mentioned in the closed issue https://github.com/beyondcode/laravel-websockets/issues/301#issuecomment-722956577

``` json
  Illuminate\Contracts\Container\BindingResolutionException

  Target [Symfony\Component\Console\Output\OutputInterface] is not instantiable while building [BeyondCode\LaravelWebSockets\Server\Loggers\WebSocketsLogger].

  at vendor/laravel/framework/src/Illuminate/Container/Container.php:1038
    1034▕         } else {
    1035▕             $message = "Target [$concrete] is not instantiable.";
    1036▕         }
    1037▕
  ➜ 1038▕         throw new BindingResolutionException($message);
    1039▕     }
    1040▕
    1041▕     /**
    1042▕      * Throw an exception for an unresolvable primitive.

      +19 vendor frames
  20  routes/web.php:31
      Illuminate\Support\Facades\Facade::__callStatic("get")

      +4 vendor frames
  25  app/Providers/RouteServiceProvider.php:49
      Illuminate\Routing\RouteRegistrar::group("/var/www/grabber/routes/web.php")
```

**Comment by Amirilidan78** [comment]
any temp solution ?

**Comment by rennokki** [comment]
@Amirilidan78 Can you share the code that is giving you troubles? Make sure to read this comment: https://github.com/beyondcode/laravel-websockets/pull/662#issuecomment-773428758

**Comment by TimVanHerwijnen** [comment]
I'm trying to find out why it throws that error but since I don't have a great understanding of how Interfaces and stuff work I've figured out a bypass.

My theory why this happens is maybe because of `OutputInterface`* gets defined twice if you have 2 wsHandlers?
*`vendor\beyondcode\laravel-websockets\src\Server\Loggers\Logger.php:49`

To stop this from happening I commented out these lines in `vendor\beyondcode\laravel-websockets\src\Server\Router.php` (155-157):
```
// if (WebsocketsLogger::isEnabled()) {
//     $app = WebsocketsLogger::decorate($app);
// }
```

The downside to this is that you have no logs in the terminal of whats happening except for the "Saving statistics..." messages. But it IS actually running and can be used since I can access the dashboard and connect with it.
