### ISSUE TITLE
Event not emited to websockets from job

### ISSUE THREAD

**Issue by mainshooter** [beyondcode/laravel-websockets#691]
I'm trying to send a event from a job. Sending that events works outside the job. But if I try to emit the event from inside the job, it does not emit.

Could you please help me?

Thank you,

**Comment by tonysm** [comment]
Did you change your broadcasting configuration while the WS server was running? I vaguely remember having to restart the WS server after changing it to point to the new WS server (instead of sending to Pusher)

**Comment by mainshooter** [comment]
No configuration was changed. When I trigger a event to call a HTTP request and in the method of the controller the event is triggered and dispatched to webbrowser clients

**Comment by pmpato** [comment]
I know this is pretty old, but in my case i had to use `php artisan queue:work --queue=default,secondary_queue`, and `MyJob::dispatch($exampleId)->onQueue('secondary_queue');`

This is because Laravel uses the `default ` queue for websockets events, and if you don't define a different queue for your jobs, the `default ` will by busy by current job, and the WS events won't fire until job is done.
