### ISSUE TITLE
stucked time to time

### ISSUE THREAD

**Issue by n0n0n0n0** [beyondcode/laravel-websockets#72]
websockets are stucked time to time and not accepting connections. i'm not sure what can cause that behaviour
i have cloudflare > nginx > websocket
cloudflare not free plan so it works well, nginx time to time showing me bad gateway cuz he cant connect to websocket, nginx config:
```
server {
    listen 2053 ssl;
    server_name host.org www.host.org;

    ssl_certificate /etc/letsencrypt/live/host.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/host.org/privkey.pem;
    ssl_trusted_certificate /etc/letsencrypt/live/host.org/chain.pem;

    ssl_stapling on;
    ssl_stapling_verify on;

    add_header Strict-Transport-Security "max-age=31536000";

    add_header Content-Security-Policy "img-src https: data:; upgrade-insecure-requests";

    location / {
	proxy_pass             http://127.0.0.1:6001;
	proxy_set_header Host  $host;
	proxy_read_timeout     1h;
	proxy_connect_timeout  5;
	proxy_redirect         off;

	# Allow the use of websockets
	proxy_http_version 1.1;
	proxy_set_header Upgrade $http_upgrade;
	proxy_set_header Connection 'upgrade';
	proxy_set_header Host $host;
	proxy_cache_bypass $http_upgrade;
  }
}
```

**Comment by stayallive** [comment]
If nginx is showing you `502 Bad Gateway` errors it might be because your websockets server is either not running, has crashed or is restarting (auto deploy script!?).

You might want to check the output of the `php artisan websockets:serve` and the Laravel logs to see if there is something useful on why the process might have crashed if you can't connect.

Config looks fine so I doubt it;s on the nginx side, but it might be something with Cloudflare - nginx - websockets server causing weirdness. (for people that don;t know, 2053 is an [allowed SSL port for cloudflare](https://support.cloudflare.com/hc/en-us/articles/200169156-Which-ports-will-Cloudflare-work-with-))

So important to note if Cloudflare is throwing 502's or nginx is. Since if Cloudflare can't connect to your server your provider's connection to cloudflare might be bad, but if it's a regular nginx 502 error it's on your server side and probably not the nginx config since I'm (and I know a lot others) are using the exact same config for proxying.

**Comment by n0n0n0n0** [comment]
It's mine nginx showed 502, not cloudflare's one.

I've put websockets w/o nginx now. So it's cloudflare > websockets.

Time to time i see
```
WebSocket connection to 'wss://host.org:2053/app/host-key?protocol=7&client=js&version=3.2.4&flash=false' failed: WebSocket opening handshake timed out
createWebSocket @ app-b25c551e58.js:57020
app-b25c551e58.js:57020 WebSocket connection to 'wss://host.org:2053/app/host-key?protocol=7&client=js&version=3.2.4&flash=false' failed: WebSocket opening handshake timed out
```
And few exceptions in log:
```
[2018-12-26 09:05:28] production.ERROR: Invalid socket ID undefined {"exception":"[object] (Pusher\\PusherException(code: 0): Invalid socket ID undefined at /home/host/vendor/pusher/pusher-php-server/src/Pusher.php:290)
[stacktrace]
#0 /home/host/vendor/pusher/pusher-php-server/src/Pusher.php(491): Pusher\\Pusher->validate_socket_id('undefined')
```
```
[2018-12-26 09:17:47] production.ERROR:  {"exception":"[object] (Illuminate\\Broadcasting\\BroadcastException(code: 0):  at /home/host/vendor/laravel/framework/src/Illuminate/Broadcasting/Broadcasters/PusherBroadcaster.php:117)
[stacktrace]
#0 /home/host/vendor/laravel/framework/src/Illuminate/Broadcasting/BroadcastEvent.php(48): Illuminate\\Broadcasting\\Broadcasters\\PusherBroadcaster->broadcast(Array, 'App\\\\Events\\\\Dial...', Array)
```

**Comment by n0n0n0n0** [comment]
So even laravel locally cant broadcast event. Websockets are running ofc:

tcp        0      0 0.0.0.0:2053            0.0.0.0:*               LISTEN      61873/php

**Comment by n0n0n0n0** [comment]
just for test i'll get free pusher.com plan and see will be here any difference or not.

**Comment by FMagnanWD** [comment]
### ### ### 

> _****_
