### ISSUE TITLE
Using a reverse proxy with valet

### ISSUE THREAD

**Issue by jonnywilliamson** [beyondcode/laravel-websockets#77]
Hi,

I made an [issue over on the valet github repo](https://github.com/laravel/valet/issues/697) as there's a strong cross over between the issues I'm having.

I've just recently started to run Valet for my development and I would like to upgrade my app to use this websocket package.

The docs for the websocket server seem to allow a few things 

- [Valet usage with SSL certificates](https://docs.beyondco.de/laravel-websockets/1.0/basic-usage/ssl.html#usage-with-laravel-valet)
- [Reverse proxy access using nginx](https://docs.beyondco.de/laravel-websockets/1.0/basic-usage/ssl.html#same-location-for-websockets-and-web-contents).

My previous development was on windows with Homestead, and I was using a reverse proxy on nginx to forward all my websocket connections through nginx to the echo webserver. This was brilliant and clean and was working flawlessly for me. It also allowed the code to match between my development and production servers.

I'm currently completely halted in my development with valet because I can't seem to recreate this. Is there anyway to allow Reverse Proxy access using Valet - which would be a mix of the above 2 options?

Thanks if you can point me in the right direction.

**Comment by stayallive** [comment]
I think the issue over at valet will be of more help than here :)

This is very Valet specific and this package is not going to be able to do much (apart from maybe documenting the solution) to make it any easier/possible.

I personally made the websockets server url for my app configurable using a value in the `.env`. This made all options I would want to change locally configurable through the `.env`. Also added a `-local` broadcast driver to disable the SSL verification. (also allowed myself to disable websockets locally since i'm not always running `websockets:serve`)
