### ISSUE TITLE
Can I use this without pusher?

### ISSUE THREAD

**Issue by Ghustavh97** [beyondcode/laravel-websockets#821]
Is it possible to use this package without having to use pusher kinda like `laravel-echo-server` allows you to do? If so how do I configure an app in `websockets.php`?

```php
    'apps' => [
        [
            // 'id' => env('PUSHER_APP_ID'),
            'name' => env('APP_NAME'),
            // 'key' => env('PUSHER_APP_KEY'),
            // 'secret' => env('PUSHER_APP_SECRET'),
            // 'path' => env('PUSHER_APP_PATH'),
            'capacity' => null,
            'enable_client_messages' => false,
            'enable_statistics' => true,
        ],
    ],
```

I tried just disabling the ones that required pusher but it looks like those are required.

**Comment by calebanthony** [comment]
Follow the instructions here: https://beyondco.de/docs/laravel-websockets/basic-usage/pusher

**Comment by Ghustavh97** [comment]
@calebanthony thanks. The way the docs were worded made it sound like I needed pusher to make it work.

**Comment by agent306** [comment]
Please update the documents at [https://beyondco.de/docs/laravel-websockets/basic-usage/pusher](https://beyondco.de/docs/laravel-websockets/basic-usage/pusher) so that skimmers (like most of us) don't get the idea that this won't work without Pusher configs. Not all of us read the documents word by word. Even so, I had to read every single line of your paraph over paragraph to make it work without registering an instance at Pusher. Very pooly written document. Sometimes it feels like the documentation is a product of paid work BY pusher that discourages skimmers to use this replacement.
