### ISSUE TITLE
How to Authenticate from Vue

### ISSUE THREAD

**Issue by matze1708** [beyondcode/laravel-websockets#827]
Hello,
I have a Laravel API backend and a Vue front end.

I have now got it working so that the back end and front end talk to each other via the Pusher API. 

But what do I need to do to authenticate the private channels?

I would prefer to authenticate with the Bearer Token. 
To do this, in the BroadCastServiceProvider. 

```
`public function boot()
    {
        Broadcast::routes(['middleware' => ['auth:api']]);
//        Broadcast::routes();

        require base_path('routes/channels.php');
    }`
```

I tried to exclude the route /broadcasting/auth in the VerfiyCSRFToken

```
`    protected $except = [
        '/broadcasting/auth'
    ];`
```

On the front end side, I did it this way:

websocket.js ( Modul):
```
`export default new Pusher(
    process.env.VUE_APP_PUSHER_APP_KEY,
    {
            wsHost: process.env.VUE_APP_PUSHER_URL,
            wsPort: process.env.VUE_APP_PUSHER_PORT,
            forceTLS: false,
            cluster: process.env.VUE_APP_PUSHER_APP_CLUSTER,
            // authEndpoint: '/auth',
            authEndpoint: 'http://localhost/broadcasting/auth',
            auth: {
                headers: {
                    Authorization: '',
                },
            },
            enabledTransports: ['ws', 'flash'],
    },
);`
```

```
subscribe() {
      pusher.config.auth.headers.Authorization = `Bearer ${this.$store.state.profile.apiToken}`;
      pusher.subscribe('private-GAUpdate');
      console.log(pusher.config);
      pusher.bind('App\\Events\\GAUpdate', (data) => {
        // console.log(data.message);
          if (this.$store.state.controls.Control[data.message.utControl2Room_ID]) {
          this.$store.commit('controls/setControl', {
            C2RID: data.message.utControl2Room_ID,
            value: data.message.data,
          });
        }
      });
    },
```

But I get error 403 forbidden

What do I have to do?

I do not have a CSRF token due to the front end back end structure.

Thank you

**Comment by butaminas** [comment]
I had the same issue and this is how I fixed it.
However, in my case, `/broadcasting/auth` request are handled by Laravel Echo but the idea should be the same.

Set **/app/Providers/BroadcastServiceProvider.php** to:
```
    public function boot()
    {
        Broadcast::routes(['middleware' => ['api']]);

        require base_path('routes/channels.php');
    }
```

Then, after logging in and receiving the JWT token I had to update `Laravel Echo` config like so:
`window.Echo.options.auth.headers.Authorization = 'Bearer ' + <new token>`

It might be a differently on your end if you don't use Laravel Echo but the important thing to note is that this has to be the first thing you do after successful log in request, otherwise, you may send request to `/broadcasting/auth` with no auth token and get the 403 error.

Hope it helps!
