### ISSUE TITLE
Statistic Dashboard not found

### ISSUE THREAD

**Issue by FredZockt** [beyondcode/laravel-websockets#831]
"laravel/framework": "^8.54"
"beyondcode/laravel-websockets": "^2.0@beta"

when starting the websocket server at port 6001 everything seems to run normal:
Starting the WebSocket server on port 6001...

and after some time it says:
Saving statistics...

but for some reason I am unable to access any page under the 6001 port.
even /laravel-websockets is resolved as a 404.

Does anybody has an advice what to do?

**Comment by kamz8** [comment]
HI,
I have a same problem  with dashboard. Server is running, and can connect 
![obraz](https://user-images.githubusercontent.com/15749276/130260738-d960dc29-73ab-49c6-95bb-78f191fceb02.png)
![obraz](https://user-images.githubusercontent.com/15749276/130260842-a422c192-80ce-4fa9-bcb2-eecab3b53b16.png)

`"beyondcode/laravel-websockets": "2.*", `
`"laravel/framework": "^8.40",`

I commented on all mine routes and dashbord is not present.

**Comment by madeadi** [comment]
This is the solution. 

Look at line 12. You need to add that `path`. 
![image](https://user-images.githubusercontent.com/478268/152209715-c8f541b8-9d14-4950-a138-1499370cb925.png)

That's because in the `WebSocketsServiceProvider`, the `Route::group` is trying to find `config('websockets.dashboard.path')`.

I'm using `dev-master` branch. I think it's version 2.
